### ISSUE TITLE
Not work for custom post types

### ISSUE THREAD

**Issue by drpshtiwan** [DalkMania/wp-graphql-mb#1]
I tried to use on custom post type fields but it didn't work, Can you fix this feature too?

**Fix**
Fixed by commenting unset when check show_in_rest property
```
foreach ($types as $type => $object) {
    if (empty($object->show_in_rest)) {
        // unset($types[$type]);
    }
}
```

**Comment by DalkMania** [comment]
Thanks for this. It should be fixed now :)
