### ISSUE TITLE
Does this Plugin still work?

### ISSUE THREAD

**Issue by creazy231** [DalkMania/wp-graphql-mb#2]
The title is the question because I can't get content from my custom fields.

**Comment by DalkMania** [comment]
@creazy231 

Looks like the wp-graphql api changed since 0.3. It should work with versions prior to that.

**Comment by creazy231** [comment]
Thanks (:
Any plans to update the plugin for the newest version?

**Comment by DalkMania** [comment]
@creazy231 working on it. I'll see if I have some time this weekend :)

**Comment by DalkMania** [comment]
@creazy231 

Hey I did some work on it. You should be able to get some results on your queries now.
