### ISSUE TITLE
Is this actively used?

### ISSUE THREAD

**Issue by hsimah** [DalkMania/wp-graphql-mb#3]
Hi - I am the author of [wp-graphql-metabox](https://github.com/hsimah/wp-graphql-metabox).

I am looking for help making it a full and robust solution to getting MB fields and types into WPGraphQL. If you'd like to partner up you can find me on [Slack](https://wp-graphql.slack.com/archives/CJ6EXQX4L).

**Comment by DalkMania** [comment]
@hsimah Sure thing. I used a while back. But not so much anymore, I do try to keep it current as often as I can. I will find you on Slack for sure. Thanks for reaching out :)
